### ISSUE TITLE
Change folder dist

### ISSUE THREAD

**Issue by netbasejsc** [ahmadawais/create-guten-block#150]
Hi,

I want to change dist folder to
- assets/js/blocks.build.js
- assets/css/blocks.editor.build.css
- assets/css/blocks.style.build.css

How to change it?

Thank you so much!

**Comment by netbasejsc** [comment]
Hey ahmadawais, why you closed this question but not aswser?

**Comment by RodrigoDAgostino** [comment]
@netbasejsc I'm pretty sure Ahmad is not happy with you making changes like that, but I totally get you, mate.

To do what you're attempting to do, go and dig a little bit inside the `node_modules/cgb-scripts/config` folder. Look for these two files: `webpack.config.dev.js` and `webpack.config.prod.js`. Modify the paths and file names as you please :)

**Comment by ahmadawais** [comment]
@netbasejsc I closed the issue because it's not an issue it's a support request and my schedule is filled. If you need priority support [kindly pay for my time](https://github.com/ahmadawais/create-guten-block#support-our-open-source-projects-).

Since now I have time. You will have to eject the app and change the webpack configuration that way you can change the directory. `create-guten-block` by default is meant to be configuration-free.

Peace! ✌️
