### ISSUE TITLE
i18n: Add support for Text Domains

### ISSUE THREAD

**Issue by grappler** [ahmadawais/create-guten-block#23]
The strings in the internationalization functions of `block.js` need to have a text domain. e.g `__( 'CGB Example' )`.

The plugin slug can be easily used for this.

**Comment by ahmadawais** [comment]
@grappler Thanks for dropping by. Would love to see you contribute to this project.

I don't think so that the `__()` function can take another argument. That's not how it's implemented.

```js
 export function __( text ) { 
 	return getI18n().gettext( text ); 
 } 
```

https://github.com/WordPress/gutenberg/blob/f36477830b15762755fc06a55359fd8d952776ca/i18n/index.js#L33-L44

But I am open to suggestions here. I think we can ask @ntwb about this. 🤔

**Comment by grappler** [comment]
It seems you are right. In the i[18n readme](https://github.com/WordPress/gutenberg/tree/master/i18n) there is:

> Note that you will not need to specify domain for the strings.

It seems like there is an issue that there is no place to define the textdomain yet https://github.com/WordPress/gutenberg/issues/4147.

The reason that I thought there was a text domain there was that the few code examples that I saw added the text domain. 

I think there was some confusion also with the JS i18n features discussed for core. https://make.wordpress.org/core/2016/10/10/javascript-internationalization/

**Comment by ahmadawais** [comment]
We can work on generating a .pot file but this one seems to be addressed. I hope you'll contribute.
