### ISSUE TITLE
Any change I make disables existing blocks.

### ISSUE THREAD

**Issue by michaelslevy** [ahmadawais/create-guten-block#269]
Any change I make, even just a CSS rule, invalidates existing instances of the block after `npm run build`. Is there a way to prevent this?

Michael

**Comment by ahmadawais** [comment]
That is how Gutenberg is built. To solve it we need hot reloading of blocks in both JavaScript and PJP. For that, I need to spend a good amount of time on this project. I don't have the support to do that. I know it sucks. Hoping to solve it but the WordPress community seldom invests in Developer Tooling which is why it's hard to build with WP + React.
