### ISSUE TITLE
package name is appended with -cgb-guten-block 

### ISSUE THREAD

**Issue by rajamohammed** [ahmadawais/create-guten-block#33]
Tried the installation with a [path to the plugin], The package.json is taking up the entire path as the name of the package and appends it with '-cgb-guten-block' in v 1.9.2.  

on mac terminal
node -v8.6.0
npm -v5.3.0
 npm ls cgb-scripts
/Users/rajamohammed/Sites/wp-test/wp-content/plugins/my-gt-blocks
└── cgb-scripts@1.9.4 

npm ERR! error in /Users/rajamohammed/Sites/wp-test/wp-content/plugins/my-gt-blocks: Invalid name: "./wp-content/plugins/my-gt-blocks-cgb-guten-block"

changing the name in package.json resolved my issue.

**Comment by ahmadawais** [comment]
@rajamohammed I am unable to understand what's the issue is here. Can you share what is the problem and how I can reproduce it? Also how did you fix it.

**Comment by rajamohammed** [comment]
The command `create-guten-block ./wp-content/plugins/new-guten` is run from wp root , 

which creats a package 

  ```
"name": "./wp-content/plugin/new-guten-cgb-guten-block",
   
```
whereas the  pacakge name is expected to be **new-guten**

While doing  npm start from the new-guten plugin directory encountered the error below

 `npm ERR! error in /Users/rajamohammed/Sites/wp-test/wp-content/plugins/my-gt-blocks: Invalid name: "./wp-content/plugins/my-gt-blocks-cgb-guten-block"`
 
Not sure why it adds -cgb-guten-block to directory and package name with the path, since it is a global script it would be good to have a optional path param while doing  create-guten-block

**Comment by ahmadawais** [comment]
@rajamohammed That's happening because you are sending a path in place of the name of your block. Path doesn't work. There's a lot of `path` resolution happening behind the scene, so I suggest you read the documentation and follow it. 

As stated in the docs on the `readme.md` 

⚠️ Make sure run this command in your local WordPress install's plugins folder i.e. /local_dev_site.tld/wp-content/plugins/ folder — since this command will produce a WordPress plugin that you can go to WP Admin ▶︎ Plugins to activate.

Moreover, it's not a global script. The installation is global which is planned to be deprecated soon and we'll be using `npx` to install and run it from the next version as noted in #13
