### ISSUE TITLE
Error on templatePromise - When creating plugin files

### ISSUE THREAD

**Issue by owllux** [ahmadawais/create-guten-block#34]
Getting Error while creating new plugin/block.

Error: EISDIR

![block error](https://user-images.githubusercontent.com/9252561/36205946-a4ca688a-11b6-11e8-9c9c-d7734685ea1e.png)

Sys Info:
Windows 10 (64 bit)
node - 9.3.0
npm - 5.6.0

**Comment by ahmadawais** [comment]
The screenshot is good but I need you to paste all of that in a comment here, and tell me how and what you did to reproduce this error.

**Comment by owllux** [comment]
Installed create-guten-block through npm
`npm install create-guten-block --global`

Then in wp plugins folder called
`create-guten-block block18`

Screencast of the process is attached below, Please have a look.

![cmd_record_guten_block](https://user-images.githubusercontent.com/9252561/36239876-1eccf252-1233-11e8-8363-27b4d07e9887.gif)

And cmd console text is

```
??   Creating a WP Gutenberg Block plugin called:  block18

 In the directory: E:\xampp\htdocs\wpdev\wp-content\plugins\block18
 This might take a couple of minutes.

v 1. Creating the plugin directory called ?  block18
v 2. Installing npm packages...
- 3. Creating plugin files...ERROR on templatePromise ? { Error: EISDIR: illegal operation on a directory, readlink 'E:\xampp\htdocs\wpdev\wp-content\plugins\block18'
    at Object.fs.readlinkSync (fs.js:987:18)
    at checkDest (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\fs-extra\lib\copy-sync\copy-sync.js:183:23)
    at onDir (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\fs-extra\lib\copy-sync\copy-sync.js:110:24)
    at getStats (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\fs-extra\lib\copy-sync\copy-sync.js:48:32)
    at startCopy (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\fs-extra\lib\copy-sync\copy-sync.js:41:10)
    at Object.copySync (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\fs-extra\lib\copy-sync\copy-sync.js:36:10)
    at resolve (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\cgb-scripts\scripts\init.js:51:7)
    at new Promise (<anonymous>)
    at copyTemplateFiles (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\cgb-scripts\scripts\init.js:46:26)
    at module.exports (E:\xampp\htdocs\wpdev\wp-content\plugins\block18\node_modules\cgb-scripts\scripts\init.js:175:8)
  errno: -4068,
  code: 'EISDIR',
  syscall: 'readlink',
  path: 'E:\\xampp\\htdocs\\wpdev\\wp-content\\plugins\\block18' }
```

Sys Info:
Windows 10 (64 bit)
node - 9.3.0
npm - 5.6.0

**Comment by ahmadawais** [comment]
Yeah, it looks like since you're using windows a package called `fs-extra` is unable to perform this 

```js
fs.copySync( template, blockDir );
```

Which is meant to copy the template files into the directory you just created. Everything else is working. Pretty sure it's related to Windows and I don't use one.

@MrSaqibAmeen can you test this?

**Comment by ahmadawais** [comment]
EISDIR stands for "Error, Is Directory". This means that NPM is trying to do something to a file but it is a directory. In your case, NPM is trying to "read" a file which is a directory (Line: 4). Since the operation cannot be done the error is thrown.

Three things to make sure here.

Make sure the file exists. If it does not, you need to create it. (If NPM depends on any specific information in the file, you will need to have that information there).
Make sure it is in fact a file and not a directory.
It has the right permissions. You can change the file to have all permissions with "sudo chmod 777 FILE_NAME". (Careful: You are giving Read, Write and Execute permissions to every one on that file)

Now without a Windows system, I can't debug that.

**Comment by MrSaqibAmeen** [comment]
@ahmadawais I am currently using Win 8.1 – have some issues with windows 10 on my machine. 

Give me some time, I will try on some other machine with windows 10 and get back to you.

**Comment by MrSaqibAmeen** [comment]
Works perfectly fine for me on Windows 10.
npm v: `5.6.0`
node v: `9.5.0`

![image](https://user-images.githubusercontent.com/31374163/36339596-2f548a90-13eb-11e8-827f-a68bf9ccf994.png)

**Comment by ahmadawais** [comment]
@owllux it looks like the issue is specific to you only as at Win 10 it's working. What more can you share?

**Comment by owllux** [comment]
@ahmadawais @mrsaqibameen Thank you for the reply.

- Cleared cache and upgraded node to 9.5.0
- Tried to copy the template directory manually

but nothing helped.

Will try on another PC or VM.

**Comment by youngmicroserf** [comment]
@owllux did you manage to solve this?

I'm having the exact same problem on win 10 64bit current node/npm , cgb 1.13.0.

Thanks!

**Comment by youngmicroserf** [comment]
I eventually managed to solve this: it's an error that occured when I tried to use create-guten-block from within a directory that is *not* the home drive. In other words creating the block scaffolding on c:/ works, creating it on o:/ throws errors, for some unknown reason.
