### ISSUE TITLE
SCSS Files not compiling at all.

### ISSUE THREAD

**Issue by EpicWebs** [ahmadawais/create-guten-block#44]
I have been using the Create Guten Block and it's awesome, thanks!

I went to try and update some of the CSS but the .scss files are not compiling into the .css files inside the build folder. I am not sure if I need to be running SASS, or install something else to get it working correctly?

Any help would be much appreciated!

### Environment

1. `node -v`: v9.7.1
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system: Windows
2. Browser and version (if relevant): Firefox (not relevant)

### Steps to Reproduce

1. Delete all of the current CSS inside the .scss files
2. Run the command npm run build
3. Open the .css files

### Expected Behavior

When running the command npm run build the .scss files would compile into .css files.

### Actual Behavior

The .css files still contain old CSS and not the updated CSS from the .scss files.

**Comment by asharirfan** [comment]
Hi @EpicWebs 

I am sorry that you're having this issue. You don't need to install anything to compile SCSS.

Everything works out of the box in create-guten-block because it is a zero-configuration #0CJS developer toolkit 💯 

I am not able to reproduce the issue you have mentioned.

Have you tried using `npm start` command? If not, then can you please test and let me know the results?

👉  You can read more about the workflow of create-guten-block over here: https://github.com/ahmadawais/create-guten-block#workflow

Cheers!

**Comment by ahmadawais** [comment]
@EpicWebs That's very kind of you to say! 💯

I can assure you that `scss` files do compile to `css` automatically.

Take a look at this example https://github.com/ahmadawais/create-guten-block/tree/master/examples/01-single-block

Makes sure you .scss files are included in your block.js file like https://github.com/ahmadawais/create-guten-block/blob/master/examples/01-single-block/src/block/block.js#L8-L10

Also for adding css that's common to all the blocks you can use common.css file inside source folder.

**Comment by EpicWebs** [comment]
Thank you, I'll take a look again when I am next at my project! I did believe that the scss should compile automatically I just couldn't get it working for some reason.
